name: breakout_solution
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - asttokens=2.4.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - comm=0.2.2
  - contourpy=1.2.0
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.0
  - cuda-version=12.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.6
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - farama-notifications=0.0.4
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gymnasium=0.28.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jax-jumpy=1.0.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.2.65
  - libcufft=11.2.0.44
  - libcufile=1.11.1.6
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcusolver=11.6.0.99
  - libcusparse=12.3.0.142
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnpp=12.2.5.2
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.99
  - libnvjpeg=12.3.1.89
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - nose=1.3.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiosignal==1.3.1
      - ale-py==0.8.1
      - attrs==24.2.0
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - click==8.1.7
      - decorator==4.4.2
      - dm-tree==0.1.8
      - ffmpeg==1.4
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - ipywidgets==8.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - lazy-loader==0.4
      - lz4==4.3.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - moviepy==1.0.3
      - msgpack==1.1.0
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - proglog==0.1.10
      - protobuf==5.28.2
      - pyarrow==17.0.0
      - pytz==2024.2
      - ray==2.37.0
      - referencing==0.35.1
      - rich==13.9.2
      - rpds-py==0.20.0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - shellingham==1.5.4
      - shimmy==0.2.1
      - stable-baselines3==2.3.2
      - tensorboardx==2.6.2.2
      - tifffile==2024.9.20
      - tqdm==4.66.5
      - typer==0.12.5
      - tzdata==2024.2
      - unrar==0.4
      - widgetsnbextension==4.0.13
prefix: /home/zhiyang/programs/anaconda3/envs/class_rl
